[package]
name = "imagine"
version = "0.0.6-alpha.0"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
bytemuck = "1"
miniz_oxide = { version = "0.5", default-features = false, optional = true }

[features]
default = ["png"]
alloc = []
png = ["miniz_oxide"]

[dev-dependencies]
#pixels = "0.8"
pixels = { git = "https://github.com/parasyte/pixels", branch="feature/clear-color" }
winit = "0.25"
