[package]
name = "imagine"
version = "0.0.6-alpha.0"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]

[dev-dependencies]
fermium = { version = "20014", features = ["experimental_fast_build"] }
gl33 = "0.2"
